#!/usr/bin/env python

import Pyro4
from simple_camera_capture.gui import CaptureGUI
from threading import Thread
import sys
import logging


def main():

    port = int(sys.argv[1])

    logger = logging.getLogger()
    logger.setLevel(logging.INFO)

    ns = Pyro4.locateNS(port=port)

    pyro_uri = ns.lookup('org.coxlab.camera_capture.controller')
    controller = Pyro4.Proxy(pyro_uri)

    print controller

    gui = CaptureGUI(controller)

    gui.mainloop()


if __name__ == '__main__':
    main()
