#!/bin/bash

# PYOPENCL_CTX=2

export PYRO_SERIALIZER=pickle
export PYRO_SERIALIZERS_ACCEPTED=pickle


port=$RANDOM
quit=0

while [ "$quit" -ne 1 ]; do
  netstat -a | grep $port >> /dev/null
  if [ $? -gt 0 ]; then
    quit=1
  else
    port=`expr $port + 1`
  fi
done


LAUNCH_NS="python -Wignore -m Pyro4.naming --port=$port"
echo "Launching Pyro name server..."
echo ${LAUNCH_NS}
eval ${LAUNCH_NS} &

sleep 2

echo "Starting eyetracker"
ENGINE="simple_camera_capture_engine $port"
eval ${ENGINE} &

sleep 5

echo "Starting GUI"
GUI="simple_camera_capture_gui $port"
eval ${GUI}


sleep 2
echo "Done."

NS_PID=`ps ax | grep -e "Pyro4.naming" | grep -v grep | awk '{print $1}'`
ENGINE_PID=`ps ax | grep -e "${ENGINE}" | grep -v grep | awk '{print $1}'`

echo "Killing launched background processes."
kill $NS_PID
kill $ENGINE_PID